// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Footer } from "../users";
import Navbar from "../navbar";
import MaxWidthWrapper from "./maxwidthwrapper";
// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: "Admin Dashboard",
//   description: "Generated by create next app",
// };

export default function UserLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Navbar />
      {/* <div className="container mt-8 md:px-8 2xl:px-16"> */}
      <MaxWidthWrapper className="mt-8">
        {children}
        {/* <Footer /> */}
      </MaxWidthWrapper>
      {/* </div> */}
      <Footer />
    </>
  );
}

// export default function DashboardLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <section className="flex flex-col min-h-screen">
//       <Sidebar />
//       <main
//         className="relative grow"
//         style={{ minHeight: "-webkit-fill-available" }}
//       >
//         <div className="w-full mx-auto">{children}</div>
//       </main>
//     </section>
//   );
// }
